apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-prod"},"spec":{"acme":{"email":"shrutivij15@gmail.com","privateKeySecretRef":{"name":"letsencrypt-prod-private-key"},"server":"https://acme-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"nginx"}}}]}}}
  creationTimestamp: "2022-08-02T11:47:00Z"
  generation: 1
  name: letsencrypt-prod
  resourceVersion: "1154595"
  uid: 37f88589-f447-4d71-aca4-177016cf9e42
spec:
  acme:
    email: shrutivij15@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status:
  acme:
    lastRegisteredEmail: shrutivij15@gmail.com
    uri: https://acme-v02.api.letsencrypt.org/acme/acct/658569876
  conditions:
  - lastTransitionTime: "2022-08-02T11:47:02Z"
    message: The ACME account was registered with the ACME server
    observedGeneration: 1
    reason: ACMEAccountRegistered
    status: "True"
    type: Ready
